apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.17.0 (a74acad)
  creationTimestamp: null
  labels:
    io.kompose.service: archivematica-mcp-server
  name: archivematica-mcp-server
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: archivematica-mcp-server
    spec:
      containers:
      - env:
        - name: ARCHIVEMATICA_MCPSERVER_CLIENT_DATABASE
          value: MCP
        - name: ARCHIVEMATICA_MCPSERVER_CLIENT_HOST
          value: mysql
        - name: ARCHIVEMATICA_MCPSERVER_CLIENT_PORT
          value: "62001"
        - name: ARCHIVEMATICA_MCPSERVER_CLIENT_PASSWORD
          value: demo
        - name: ARCHIVEMATICA_MCPSERVER_CLIENT_USER
          value: archivematica
        - name: ARCHIVEMATICA_MCPSERVER_MCPSERVER_MCPARCHIVEMATICASERVER
          value: gearmand:4730
        - name: ARCHIVEMATICA_MCPSERVER_SEARCH_ENABLED
          value: "true"
        - name: DJANGO_SECRET_KEY
          value: "12345"
        - name: DJANGO_SETTINGS_MODULE
          value: settings.common
        image: archivematica-mcp-server:local
        name: archivematica-mcp-server
        imagePullPolicy: Never
        resources: {}
        volumeMounts:
        - mountPath: /var/archivematica/sharedDirectory
          name: am-pipeline-data
      restartPolicy: Always
      volumes:
      - name: archivematica-mcp-server-claim0
        persistentVolumeClaim:
          claimName: archivematica-mcp-server-claim0
      - name: archivematica-mcp-server-claim1
        persistentVolumeClaim:
          claimName: archivematica-mcp-server-claim1
      - name: archivematica-mcp-server-claim2
        persistentVolumeClaim:
          claimName: archivematica-mcp-server-claim2
      - name: am-pipeline-data
        persistentVolumeClaim:
          claimName: am-pipeline-data
status: {}
