apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.17.0 (a74acad)
  creationTimestamp: null
  labels:
    io.kompose.service: gearmand
  name: gearmand
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: gearmand
    spec:
      containers:
      - args:
        - --queue-type=redis
        - --redis-server=redis
        - --redis-port=6379
        - -L 127.0.0.1
        - -p 4730
        image: artefactual/gearmand:1.1.17-alpine
        name: gearmand
        ports:
        - containerPort: 4730
          hostIP: 127.0.0.1
        resources: {}
      restartPolicy: Always
status: {}
