apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.17.0 (a74acad)
  creationTimestamp: null
  labels:
    io.kompose.service: nginx
  name: nginx
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: nginx
    spec:
      containers:
      - image: nginx:stable-alpine
        name: nginx
        ports:
        - containerPort: 80
        - containerPort: 8000
        resources: {}
        volumeMounts:
        - mountPath: /etc/nginx/nginx.conf
          name: nginx-claim0
          subPath: nginx.conf
        - mountPath: /etc/nginx/conf.d/archivematica.conf
          name: nginx-claim1
          subPath: archivematica.conf
        - mountPath: /etc/nginx/conf.d/default.conf
          name: nginx-claim2
          subPath: default.conf
      restartPolicy: Always
      volumes:
      - name: nginx-claim0
        configMap:
          name: nginx-claim0
      - name: nginx-claim1
        configMap:
          name: nginx-claim1
      - name: nginx-claim2
        configMap:
          name: nginx-claim2
status: {}
